name: mbkc_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # State management
  flutter_riverpod: ^2.3.7
  hooks_riverpod: ^2.3.8
  riverpod_annotation: ^2.1.1

  # Router
  auto_route: ^7.8.2

  # Handle exception
  fpdart: ^0.6.0

   # Networking
  retrofit: ^4.0.1
  dio: ^5.3.2
  awesome_dio_interceptor: ^1.0.0

  # Animation
  lottie: ^2.6.0
  flag: ^7.0.0
  font_awesome_flutter: ^10.5.0
  flutter_spinkit: ^5.2.0
  shimmer: ^3.0.0


  # Other
  flutter_svg: ^2.0.7
  image_picker: ^1.0.2
  carousel_slider: ^4.2.1
  timeago: ^3.5.0
  intl: ^0.18.1
  shared_preferences: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  retrofit_generator: ^7.0.8
  riverpod_generator: ^2.2.6
  auto_route_generator: ^7.3.0
  build_runner: ^2.4.6

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/
    - assets/icons/

  fonts:
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
