name: mbkc_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # State management
  flutter_riverpod: ^2.4.5
  hooks_riverpod: ^2.4.5
  riverpod_annotation: ^2.3.0

  # Router
  auto_route: ^7.8.4

  # Handle exception
  fpdart: ^1.1.0

   # Networking
  retrofit: ^4.0.3
  dio: ^5.3.3
  awesome_dio_interceptor: ^1.0.0

  # Animation
  lottie: ^2.7.0
  flag: ^7.0.0
  font_awesome_flutter: ^10.6.0
  flutter_spinkit: ^5.2.0
  shimmer: ^3.0.0
  flutter_native_splash: ^2.3.5

  # Firebase
  firebase_core: ^2.21.0
  firebase_messaging: ^14.7.3


  # Other
  image_picker: ^1.0.4
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  crypto: ^3.0.3


# config native splash
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/mbkc_logo.jpg
  android_12:
    color: "#ffffff"
    image: assets/images/mbkc_logo.jpg

# config launcher icon
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/mbkc_logo.jpg"
  min_sdk_android: 21 
   
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  retrofit_generator: ^8.0.3
  riverpod_generator: ^2.3.5
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1

  

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/icons/
    - assets/lotties/

  fonts:
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
